### ISSUE TITLE
v1.0.5无法在PNX运行

### ISSUE THREAD

**Issue by Mcayear** [SoBadFish/FishMagicItem#1]
### 报错信息
FishMagicItem_v1.0.5-SNAPSHOT.jar 无法在pnx运行
```
2022-12-29 09:53:14.727 [main] INFO  - 开启 FishMagicItem v1.0.5 中
2022-12-29 09:53:14.802 [main] INFO  - [FishMagicItem]: 正在加载鱼魔法物品!
2022-12-29 09:53:14.808 [main] INFO  - [FishMagicItem]: §e当前核心为 Nukkit
2022-12-29 09:53:14.823 [main] INFO  - [FishMagicItem]: §a加载指令集中...
2022-12-29 09:53:14.832 [main] INFO  - [FishMagicItem]: §a加载物品中...
2022-12-29 09:53:14.836 [main] INFO  - [FishMagicItem]: 载入数据中...
2022-12-29 09:53:14.851 [main] INFO  - [FishMagicItem]: 载入完成
2022-12-29 09:53:14.856 [main] INFO  - [FishMagicItem]: §a加载配方中...
2022-12-29 09:53:14.903 [main] FATAL - An error occurred while enabling the plugin FishMagicItem, 1.0.5, org.sobadfish.magicitem.MagicItemMainClass
java.lang.NullPointerException: Cannot invoke "String.split(String)" because "tag" is null
	at org.sobadfish.magicitem.files.datas.TagData.asItem(TagData.java:40) ~[?:?]
	at org.sobadfish.magicitem.files.datas.RecipeData.buildOutRecipe(RecipeData.java:165) ~[?:?]
	at org.sobadfish.magicitem.controller.RecipeController.initRecipe(RecipeController.java:35) ~[?:?]
	at org.sobadfish.magicitem.controller.MagicController.<init>(MagicController.java:89) ~[?:?]
	at org.sobadfish.magicitem.MagicItemMainClass.onEnable(MagicItemMainClass.java:20) ~[?:?]
	at cn.nukkit.plugin.PluginBase.setEnabled(PluginBase.java:105) ~[powernukkitx.jar:?]
	at cn.nukkit.plugin.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:125) ~[powernukkitx.jar:?]
	at cn.nukkit.plugin.PluginManager.enablePlugin(PluginManager.java:468) [powernukkitx.jar:?]
	at cn.nukkit.Server.enablePlugin(Server.java:1085) [powernukkitx.jar:?]
	at cn.nukkit.Server.enablePlugins(Server.java:1074) [powernukkitx.jar:?]
	at cn.nukkit.Server.<init>(Server.java:912) [powernukkitx.jar:?]
	at cn.nukkit.Nukkit.main(Nukkit.java:160) [powernukkitx.jar:?]
2022-12-29 09:53:14.914 [main] INFO  - 关闭 FishMagicItem v1.0.5 中
```

### 请求更新github仓库
仓库的版本太老了

**Comment by Mcayear** [comment]
测试了1.0.4是可以正常运行在PNX上

**Comment by Mcayear** [comment]
已解决
